### ISSUE TITLE
Different incompatible Licenses in Package

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [brunneis/ernie#19]
In your project root you have the [LICENSE file](https://github.com/labteral/ernie/blob/master/LICENSE) which is `apache-2.0`
But in your setup.py file [here](https://github.com/labteral/ernie/blob/master/setup.py#L15) and [here](https://github.com/labteral/ernie/blob/master/setup.py#L22), you have the license as `gnu-gpl-3`.

Those are incompatible and it would be great if you clarified. 

I'm also trying to use this in [nexB/scancode-results-analyzer](https://github.com/nexB/scancode-results-analyzer) and would you explain why [transformers is locked at an old version](https://github.com/labteral/ernie/blob/master/setup.py#L29)?

**Comment by brunneis** [comment]
Hi @AyanSinhaMahapatra. You are right, the actual license is Apache 2.0, which is more permissive. The version of Transformers is locked because the library has to be adapted due to recent changes that will break Ernie. I haven't had time for working on it again, but I'm willing to accept any contribution from the community in the meanwhile.
